#!/bin/bash

echo "Register nodes"

curl -X POST http://localhost:8000/register_with -H "Content-Type: application/json" -d "{\"node_address\":\"http://localhost:8001\"}"

#curl -X GET http://localhost:8000/peers
#curl -X GET http://localhost:8001/peers


curl -X GET http://localhost:8000/chain
curl -X GET http://localhost:8001/chain
